#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from podpyclient.settings import Settings
from podpyclient.podpyqt import PodpyQt
import sys
#from podpyclient.podpycurses import PodPyCurses

def start():
	prefs = Settings()
	prefs.read_prefs()
	#print prefs.__dict__
	#prefs.parse_args()
	#prefs.parse_feeds()

	if prefs.command_line:
		pass
	else:
		client = PodpyQt()
		with client:
			return client.start()

if __name__ == '__main__':
	sys.exit(start())
