# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'podpyclient/preferences_window.ui'
#
# Created: Sun Mar 16 14:47:32 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(748, 179)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(271, 161))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.port_start_spin_box = QtGui.QSpinBox(self.groupBox)
        self.port_start_spin_box.setMinimum(1)
        self.port_start_spin_box.setMaximum(65535)
        self.port_start_spin_box.setProperty("value", 6881)
        self.port_start_spin_box.setObjectName("port_start_spin_box")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.port_start_spin_box)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.port_range_spin_box = QtGui.QSpinBox(self.groupBox)
        self.port_range_spin_box.setMinimum(1)
        self.port_range_spin_box.setMaximum(65535)
        self.port_range_spin_box.setProperty("value", 118)
        self.port_range_spin_box.setObjectName("port_range_spin_box")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.port_range_spin_box)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.download_rate_spin_box = QtGui.QSpinBox(self.groupBox)
        self.download_rate_spin_box.setMinimum(-1)
        self.download_rate_spin_box.setMaximum(1000000000)
        self.download_rate_spin_box.setProperty("value", -1)
        self.download_rate_spin_box.setObjectName("download_rate_spin_box")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.download_rate_spin_box)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.upload_rate_spin_box = QtGui.QSpinBox(self.groupBox)
        self.upload_rate_spin_box.setMinimum(-1)
        self.upload_rate_spin_box.setMaximum(1000000000)
        self.upload_rate_spin_box.setProperty("value", -1)
        self.upload_rate_spin_box.setObjectName("upload_rate_spin_box")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.upload_rate_spin_box)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_path_line_edit = QtGui.QLineEdit(Dialog)
        self.save_path_line_edit.setObjectName("save_path_line_edit")
        self.horizontalLayout.addWidget(self.save_path_line_edit)
        self.save_path_push_button = QtGui.QPushButton(Dialog)
        self.save_path_push_button.setMinimumSize(QtCore.QSize(41, 27))
        self.save_path_push_button.setMaximumSize(QtCore.QSize(41, 27))
        self.save_path_push_button.setObjectName("save_path_push_button")
        self.horizontalLayout.addWidget(self.save_path_push_button)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.label.setBuddy(self.port_start_spin_box)
        self.label_2.setBuddy(self.port_range_spin_box)
        self.label_3.setBuddy(self.download_rate_spin_box)
        self.label_4.setBuddy(self.upload_rate_spin_box)
        self.label_5.setBuddy(self.save_path_line_edit)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Podpy - Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Torrent", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Port Start", None, QtGui.QApplication.UnicodeUTF8))
        self.port_start_spin_box.setToolTip(QtGui.QApplication.translate("Dialog", "start of the port range for torrent downloads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Port Range", None, QtGui.QApplication.UnicodeUTF8))
        self.port_range_spin_box.setToolTip(QtGui.QApplication.translate("Dialog", "width of the port range torrent downloads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Download Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.download_rate_spin_box.setToolTip(QtGui.QApplication.translate("Dialog", "maximum download rate for torrent downloads", None, QtGui.QApplication.UnicodeUTF8))
        self.download_rate_spin_box.setSpecialValueText(QtGui.QApplication.translate("Dialog", "Unlimited", None, QtGui.QApplication.UnicodeUTF8))
        self.download_rate_spin_box.setSuffix(QtGui.QApplication.translate("Dialog", " b/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Upload Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_rate_spin_box.setToolTip(QtGui.QApplication.translate("Dialog", "maximum upload rate for torrent downloads", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_rate_spin_box.setSpecialValueText(QtGui.QApplication.translate("Dialog", "Unlimited", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_rate_spin_box.setSuffix(QtGui.QApplication.translate("Dialog", " b/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "save Path", None, QtGui.QApplication.UnicodeUTF8))
        self.save_path_line_edit.setToolTip(QtGui.QApplication.translate("Dialog", "path, where downloaded files should be saved to", None, QtGui.QApplication.UnicodeUTF8))
        self.save_path_line_edit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "path, where downloaded files should be saved to", None, QtGui.QApplication.UnicodeUTF8))
        self.save_path_push_button.setText(QtGui.QApplication.translate("Dialog", "…", None, QtGui.QApplication.UnicodeUTF8))

